branches:
  only:
  - main
language: node_js
before_install:
- pushd ~ && curl https://s3.amazonaws.com/clubos-deploy/travis-ci/m2.tar.gz | tar
  xvz && popd
- pushd ~ && curl https://s3.amazonaws.com/clubos-deploy/travis-ci/scripts.tar.gz
  | tar xvz && popd
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 8.9.3
- npm install && ./node_modules/.bin/gulp before_install
env:
  global:
  - secure: JWQrtm5y2dNaHDqpDAhPoKJWpi8NzhL2sFiNYvskJn9WYbSe3mgHNWaLZPcAAEWLl/aCdy9L7fn31RSBAAL/8c0475GLx992p95tM7AkvGiuVrEpdXy7comxo6Pt6uJNPbjBc6H6JoKeKrNgq87EFtRWbZ/fo3fGH3IpummRnIGjKLxnyPM7sfSRgPXwVmw6M3n69+HGkXZYlrIkcoOY/wRZQKtoch8JDqORzq1Z7Nd9ZOnnlYC17MLt8pdAmO1W5ykEdnBAmK0GzLd2TP0ebVVu9WI6yviqYhLZy6AvhrgjF4X/aw5mufg9Bj7wO2Ksjw86lerOxKTFrguCC4CV9x10cQ0QNgZ5oQx0ehjegykmkIrOF1hM3V01UeVlSRVX7OQqx15/e5lORcPiWJSMj1ccWMb2oJXVD9OEyQcCO7sfzOFuN5x5UcmTbkVm3luHM88YzULxwrHFJk7gke2hHPtE3ZHA/FHWf29xKLwfc2n+RuujQ4Nl4eTDTWr8TXy4koXkwO13U/3krEY0WYEkn9j2zqdk5cCUT1hf4kWolwH7Fw33xKW1e+eFD8A4zaVHdR8/JGBqqom1C6t/TdGtJaDCjqzB/2p2U5zTvLbno4lGcI2lH9b8n6WAARLbVx4l/+c0txY8ZPtfpAns9d2fNLcmoxCStKX3yx6Xt/NGEyo=
  - secure: a+Y4omcSzNoPNBsIcD0ilMlfMj3hPWndK/21UaEC2IaAKQUx9qNCXli29narjMF1x4M+y2RkHkSdvrNulg0a1IWBvtyKU18Uy3++RMZOSHOlKEc9NZx9Ga7zbEoKbzEnVi3ECNnbekwkLQn6+j+OUzxJi4W7vyVdHDDSRPp1/aPeFWoRFLkeKeD9bmlcHbN7Csr840UZ2gyMvN6Y91mC+kBaIgX1si9TrS5G2SxpzleYaHOBYNez4jpQUPNqEtCmCGk79bPEGmTTkvZluuI9UonWLp2u04BKEmQRsfD7GPRPUeCdIrZRlvzN7ffL848N7AENJkp/ezs0obBcau23aeBuclWn9vp74ynuK4B6Rx3wVyYIw6sJxIb9eVfZr/Lb53uyrNS7SDhrH+OGZvmQAMbtANz+/7QOmEGuftBoZLGVS1cdc9jmPc/t0j8OCnANLxQWQF2EdRklOa+uE8d1Vt6W8Uh0cBLz/heMD0C/t2Ms5lXd/JmrR+EBHd4m3zJGgTZVj0d0P3qixOkiV3qHi0lSyWUpAWX2H2neS3SNeUF4IVd5M/FUqXIQ+k7YqdeXWCnNyIYvDj+UIHgEu1bEoi723BJ936tC73wsw2BXA1AK8BOY+e4eIJEI+WFTtsqMjqsjg6o27+e3Hn3q4wjMoqBoxu9q0S9T57nvAFLoqNE=
deploy:
- provider: script
  script: npm run travis-deploy
  skip_cleanup: true
  on:
    condition: "$DEPLOY = true"
    all_branches: true
- provider: script
  script: gem install 'aws-sdk-elasticbeanstalk' && ~/scripts/cleanupBeanstalk.rb
    clubos-webapp
  skip_cleanup: true
  on:
    condition: "$DEPLOY = true"
    all_branches: true
- provider: elasticbeanstalk
  zip-file: target/clubos-webapp-${NEW_VERSION_ID}.war
  only_create_app_version: true
  access-key-id: "${CI_DEPLOY_USERNAME}"
  secret-access-key: "${CI_DEPLOY_PASSWORD}"
  region: us-east-1
  app: clubos-webapp
  bucket_name: clubos-deploy
  bucket_path: travis-ci-builds/clubos-webapp
  env: clubos-test-seven
  skip_cleanup: true
  on:
    condition: "$DEPLOY = true"
    all_branches: true
- provider: script
  script: npm run deploy-elastic-beanstalk
  skip_cleanup: true
  on:
    condition: "$DEPLOY = true"
    all_branches: true
notifications:
  slack:
    rooms:
      secure: eoDc3BMU+iYvNEuOZ5V0N5L75KNyNBo6QQUs1Ykx72l+v+TboSVyilQqH9ilt+WbkGIsfDTUiJ1uAnvP+Z/YwrUzi/bYk8HLOu7OG0rsTawG1gIJbWtTqsp090Z6ZA2gBObB1sZ8/CzA/GbLAkRwJ971ZAqZju9dCIzNZ1sspn3la5xICOxkOC8+dnPotS39sNG2QZ2TAL0wt1ert/vTc3dcPgTgNpC8JD3QGdPhdrzpqRfDi3oQVHnfYW3phKN/+8f0kyKf/RvS71Y0AyKSYhqUZxr2rnxKFhwfYJf0+IfsjHMfmhLO00WlSJ5qhsts2aIkjmTIjpM6k1CjSAvnEBGeNIXDvJgnW7z+LUxDoREYmmYw55h6ALMQdCIplF/Cq2mLhoTq3FXA+mTjRSF0ExWmMrsHtiDQuOYDEoxCgROG/lqxq+8f90NOD+r/lrBPAaYcobQRjPacQ9cyauwIuuqCZaWHm+M8Vh7K5vtr8HF7iQLpwwVV2q20G5QNtcPsRW66sZe47W+oup734fzz9IAgEIT4aiRYdYrbOdHuqEPTAlcos0z77Siu2Z4McA1+rWNzL4jtbuZm2OP9OiY6Wv5WldVY52f95GSZ2HvJxQUpygjflSIrsPluST70qn+41WFBkzvkM6Q07gulHP3CXgcmeyLtmlDRt33Mhgn/asc=
    on_failure: always
    on_success: change
